HARDCODED_DEMO_TELEMETRY = {   'file_upload': [   {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'ARN',
                           'airport_name': 'Stockholm Arlanda Airport',
                           'flight_number': 'SK410',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-01-21',
                           'record_id': 'file_upload-ARN-SGHA-2.3-PASSENGER-SERVICES-01',
                           'recorded_at': '2026-01-21T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '10',
                           'supplier': 'Carrier',
                           'terminal': 'T5',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'ARN',
                           'airport_name': 'Stockholm Arlanda Airport',
                           'flight_number': 'SK411',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-01-21',
                           'record_id': 'file_upload-ARN-SGHA-2.3-RAMP-HANDLING-01',
                           'recorded_at': '2026-01-21T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '11',
                           'supplier': 'Carrier',
                           'terminal': 'T5',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'CPH',
                           'airport_name': 'Copenhagen Airport',
                           'flight_number': 'SK411',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-02-04',
                           'record_id': 'file_upload-CPH-SGHA-2.3-PASSENGER-SERVICES-02',
                           'recorded_at': '2026-02-04T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '11',
                           'supplier': 'Carrier',
                           'terminal': 'T3',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'CPH',
                           'airport_name': 'Copenhagen Airport',
                           'flight_number': 'SK412',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-02-04',
                           'record_id': 'file_upload-CPH-SGHA-2.3-RAMP-HANDLING-02',
                           'recorded_at': '2026-02-04T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '12',
                           'supplier': 'Carrier',
                           'terminal': 'T3',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'OSL',
                           'airport_name': 'Oslo Airport',
                           'flight_number': 'SK412',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-02-18',
                           'record_id': 'file_upload-OSL-SGHA-2.3-PASSENGER-SERVICES-03',
                           'recorded_at': '2026-02-18T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '12',
                           'supplier': 'Carrier',
                           'terminal': 'T1',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'OSL',
                           'airport_name': 'Oslo Airport',
                           'flight_number': 'SK413',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-02-18',
                           'record_id': 'file_upload-OSL-SGHA-2.3-RAMP-HANDLING-03',
                           'recorded_at': '2026-02-18T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '13',
                           'supplier': 'Carrier',
                           'terminal': 'T1',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'ARN',
                           'airport_name': 'Stockholm Arlanda Airport',
                           'flight_number': 'SK413',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-03-04',
                           'record_id': 'file_upload-ARN-SGHA-2.3-PASSENGER-SERVICES-04',
                           'recorded_at': '2026-03-04T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '13',
                           'supplier': 'Carrier',
                           'terminal': 'T5',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'ARN',
                           'airport_name': 'Stockholm Arlanda Airport',
                           'flight_number': 'SK414',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-03-04',
                           'record_id': 'file_upload-ARN-SGHA-2.3-RAMP-HANDLING-04',
                           'recorded_at': '2026-03-04T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '14',
                           'supplier': 'Carrier',
                           'terminal': 'T5',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'CPH',
                           'airport_name': 'Copenhagen Airport',
                           'flight_number': 'SK414',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-03-18',
                           'record_id': 'file_upload-CPH-SGHA-2.3-PASSENGER-SERVICES-05',
                           'recorded_at': '2026-03-18T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '14',
                           'supplier': 'Carrier',
                           'terminal': 'T3',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'CPH',
                           'airport_name': 'Copenhagen Airport',
                           'flight_number': 'SK415',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-03-18',
                           'record_id': 'file_upload-CPH-SGHA-2.3-RAMP-HANDLING-05',
                           'recorded_at': '2026-03-18T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '15',
                           'supplier': 'Carrier',
                           'terminal': 'T3',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'OSL',
                           'airport_name': 'Oslo Airport',
                           'flight_number': 'SK415',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-04-01',
                           'record_id': 'file_upload-OSL-SGHA-2.3-PASSENGER-SERVICES-06',
                           'recorded_at': '2026-04-01T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '15',
                           'supplier': 'Carrier',
                           'terminal': 'T1',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'OSL',
                           'airport_name': 'Oslo Airport',
                           'flight_number': 'SK416',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-04-01',
                           'record_id': 'file_upload-OSL-SGHA-2.3-RAMP-HANDLING-06',
                           'recorded_at': '2026-04-01T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '16',
                           'supplier': 'Carrier',
                           'terminal': 'T1',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'ARN',
                           'airport_name': 'Stockholm Arlanda Airport',
                           'flight_number': 'SK416',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-04-15',
                           'record_id': 'file_upload-ARN-SGHA-2.3-PASSENGER-SERVICES-07',
                           'recorded_at': '2026-04-15T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '16',
                           'supplier': 'Carrier',
                           'terminal': 'T5',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'ARN',
                           'airport_name': 'Stockholm Arlanda Airport',
                           'flight_number': 'SK417',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-04-15',
                           'record_id': 'file_upload-ARN-SGHA-2.3-RAMP-HANDLING-07',
                           'recorded_at': '2026-04-15T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '17',
                           'supplier': 'Carrier',
                           'terminal': 'T5',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'CPH',
                           'airport_name': 'Copenhagen Airport',
                           'flight_number': 'SK417',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-04-29',
                           'record_id': 'file_upload-CPH-SGHA-2.3-PASSENGER-SERVICES-08',
                           'recorded_at': '2026-04-29T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '17',
                           'supplier': 'Carrier',
                           'terminal': 'T3',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'CPH',
                           'airport_name': 'Copenhagen Airport',
                           'flight_number': 'SK418',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-04-29',
                           'record_id': 'file_upload-CPH-SGHA-2.3-RAMP-HANDLING-08',
                           'recorded_at': '2026-04-29T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '18',
                           'supplier': 'Carrier',
                           'terminal': 'T3',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'OSL',
                           'airport_name': 'Oslo Airport',
                           'flight_number': 'SK418',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-05-13',
                           'record_id': 'file_upload-OSL-SGHA-2.3-PASSENGER-SERVICES-09',
                           'recorded_at': '2026-05-13T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '18',
                           'supplier': 'Carrier',
                           'terminal': 'T1',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'OSL',
                           'airport_name': 'Oslo Airport',
                           'flight_number': 'SK419',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-05-13',
                           'record_id': 'file_upload-OSL-SGHA-2.3-RAMP-HANDLING-09',
                           'recorded_at': '2026-05-13T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '19',
                           'supplier': 'Carrier',
                           'terminal': 'T1',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'ARN',
                           'airport_name': 'Stockholm Arlanda Airport',
                           'flight_number': 'SK419',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-05-27',
                           'record_id': 'file_upload-ARN-SGHA-2.3-PASSENGER-SERVICES-10',
                           'recorded_at': '2026-05-27T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '19',
                           'supplier': 'Carrier',
                           'terminal': 'T5',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'ARN',
                           'airport_name': 'Stockholm Arlanda Airport',
                           'flight_number': 'SK420',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-05-27',
                           'record_id': 'file_upload-ARN-SGHA-2.3-RAMP-HANDLING-10',
                           'recorded_at': '2026-05-27T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '20',
                           'supplier': 'Carrier',
                           'terminal': 'T5',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'CPH',
                           'airport_name': 'Copenhagen Airport',
                           'flight_number': 'SK420',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-06-10',
                           'record_id': 'file_upload-CPH-SGHA-2.3-PASSENGER-SERVICES-11',
                           'recorded_at': '2026-06-10T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '20',
                           'supplier': 'Carrier',
                           'terminal': 'T3',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'CPH',
                           'airport_name': 'Copenhagen Airport',
                           'flight_number': 'SK421',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-06-10',
                           'record_id': 'file_upload-CPH-SGHA-2.3-RAMP-HANDLING-11',
                           'recorded_at': '2026-06-10T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '21',
                           'supplier': 'Carrier',
                           'terminal': 'T3',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'OSL',
                           'airport_name': 'Oslo Airport',
                           'flight_number': 'SK421',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-06-24',
                           'record_id': 'file_upload-OSL-SGHA-2.3-PASSENGER-SERVICES-12',
                           'recorded_at': '2026-06-24T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '21',
                           'supplier': 'Carrier',
                           'terminal': 'T1',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'OSL',
                           'airport_name': 'Oslo Airport',
                           'flight_number': 'SK422',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-06-24',
                           'record_id': 'file_upload-OSL-SGHA-2.3-RAMP-HANDLING-12',
                           'recorded_at': '2026-06-24T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '22',
                           'supplier': 'Carrier',
                           'terminal': 'T1',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'ARN',
                           'airport_name': 'Stockholm Arlanda Airport',
                           'flight_number': 'SK422',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-07-08',
                           'record_id': 'file_upload-ARN-SGHA-2.3-PASSENGER-SERVICES-13',
                           'recorded_at': '2026-07-08T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '22',
                           'supplier': 'Carrier',
                           'terminal': 'T5',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'ARN',
                           'airport_name': 'Stockholm Arlanda Airport',
                           'flight_number': 'SK423',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-07-08',
                           'record_id': 'file_upload-ARN-SGHA-2.3-RAMP-HANDLING-13',
                           'recorded_at': '2026-07-08T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '23',
                           'supplier': 'Carrier',
                           'terminal': 'T5',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'CPH',
                           'airport_name': 'Copenhagen Airport',
                           'flight_number': 'SK423',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-07-22',
                           'record_id': 'file_upload-CPH-SGHA-2.3-PASSENGER-SERVICES-14',
                           'recorded_at': '2026-07-22T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '23',
                           'supplier': 'Carrier',
                           'terminal': 'T3',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'CPH',
                           'airport_name': 'Copenhagen Airport',
                           'flight_number': 'SK424',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-07-22',
                           'record_id': 'file_upload-CPH-SGHA-2.3-RAMP-HANDLING-14',
                           'recorded_at': '2026-07-22T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '24',
                           'supplier': 'Carrier',
                           'terminal': 'T3',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'OSL',
                           'airport_name': 'Oslo Airport',
                           'flight_number': 'SK424',
                           'kpi_code': 'SGHA-2.3-PASSENGER-SERVICES',
                           'kpi_name': 'Passenger Services Turnaround Rate',
                           'measurement': 3051.0,
                           'period': '2026-08-05',
                           'record_id': 'file_upload-OSL-SGHA-2.3-PASSENGER-SERVICES-15',
                           'recorded_at': '2026-08-05T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '24',
                           'supplier': 'Carrier',
                           'terminal': 'T1',
                           'unit': 'SEK per turnaround for 0-40 seats'},
                       {   'airline_iata_code': 'SK',
                           'airline_name': 'SAS Scandinavian Airlines',
                           'airport_iata_code': 'OSL',
                           'airport_name': 'Oslo Airport',
                           'flight_number': 'SK425',
                           'kpi_code': 'SGHA-2.3-RAMP-HANDLING',
                           'kpi_name': 'Ramp Handling Turnaround Rate',
                           'measurement': 3543.0,
                           'period': '2026-08-05',
                           'record_id': 'file_upload-OSL-SGHA-2.3-RAMP-HANDLING-15',
                           'recorded_at': '2026-08-05T09:00:00',
                           'source_type': 'file_upload',
                           'stand': '25',
                           'supplier': 'Carrier',
                           'terminal': 'T1',
                           'unit': 'SEK per turnaround for 0-40 seats'}],
    'rest_api': [   {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'ARN',
                        'airport_name': 'Stockholm Arlanda Airport',
                        'event_id': 'rest_api-ARN-SGHA-2.8-DEICING-01',
                        'flight_number': 'SK410',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-01-21T09:00:00',
                        'period': '2026-01-21',
                        'source_type': 'rest_api',
                        'stand': '10',
                        'supplier': 'Carrier',
                        'terminal': 'T5',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'CPH',
                        'airport_name': 'Copenhagen Airport',
                        'event_id': 'rest_api-CPH-SGHA-2.8-DEICING-02',
                        'flight_number': 'SK411',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-02-04T09:00:00',
                        'period': '2026-02-04',
                        'source_type': 'rest_api',
                        'stand': '11',
                        'supplier': 'Carrier',
                        'terminal': 'T3',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'OSL',
                        'airport_name': 'Oslo Airport',
                        'event_id': 'rest_api-OSL-SGHA-2.8-DEICING-03',
                        'flight_number': 'SK412',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-02-18T09:00:00',
                        'period': '2026-02-18',
                        'source_type': 'rest_api',
                        'stand': '12',
                        'supplier': 'Carrier',
                        'terminal': 'T1',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'ARN',
                        'airport_name': 'Stockholm Arlanda Airport',
                        'event_id': 'rest_api-ARN-SGHA-2.8-DEICING-04',
                        'flight_number': 'SK413',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-03-04T09:00:00',
                        'period': '2026-03-04',
                        'source_type': 'rest_api',
                        'stand': '13',
                        'supplier': 'Carrier',
                        'terminal': 'T5',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'CPH',
                        'airport_name': 'Copenhagen Airport',
                        'event_id': 'rest_api-CPH-SGHA-2.8-DEICING-05',
                        'flight_number': 'SK414',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-03-18T09:00:00',
                        'period': '2026-03-18',
                        'source_type': 'rest_api',
                        'stand': '14',
                        'supplier': 'Carrier',
                        'terminal': 'T3',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'OSL',
                        'airport_name': 'Oslo Airport',
                        'event_id': 'rest_api-OSL-SGHA-2.8-DEICING-06',
                        'flight_number': 'SK415',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-04-01T09:00:00',
                        'period': '2026-04-01',
                        'source_type': 'rest_api',
                        'stand': '15',
                        'supplier': 'Carrier',
                        'terminal': 'T1',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'ARN',
                        'airport_name': 'Stockholm Arlanda Airport',
                        'event_id': 'rest_api-ARN-SGHA-2.8-DEICING-07',
                        'flight_number': 'SK416',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-04-15T09:00:00',
                        'period': '2026-04-15',
                        'source_type': 'rest_api',
                        'stand': '16',
                        'supplier': 'Carrier',
                        'terminal': 'T5',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'CPH',
                        'airport_name': 'Copenhagen Airport',
                        'event_id': 'rest_api-CPH-SGHA-2.8-DEICING-08',
                        'flight_number': 'SK417',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-04-29T09:00:00',
                        'period': '2026-04-29',
                        'source_type': 'rest_api',
                        'stand': '17',
                        'supplier': 'Carrier',
                        'terminal': 'T3',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'OSL',
                        'airport_name': 'Oslo Airport',
                        'event_id': 'rest_api-OSL-SGHA-2.8-DEICING-09',
                        'flight_number': 'SK418',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-05-13T09:00:00',
                        'period': '2026-05-13',
                        'source_type': 'rest_api',
                        'stand': '18',
                        'supplier': 'Carrier',
                        'terminal': 'T1',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'ARN',
                        'airport_name': 'Stockholm Arlanda Airport',
                        'event_id': 'rest_api-ARN-SGHA-2.8-DEICING-10',
                        'flight_number': 'SK419',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-05-27T09:00:00',
                        'period': '2026-05-27',
                        'source_type': 'rest_api',
                        'stand': '19',
                        'supplier': 'Carrier',
                        'terminal': 'T5',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'CPH',
                        'airport_name': 'Copenhagen Airport',
                        'event_id': 'rest_api-CPH-SGHA-2.8-DEICING-11',
                        'flight_number': 'SK420',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-06-10T09:00:00',
                        'period': '2026-06-10',
                        'source_type': 'rest_api',
                        'stand': '20',
                        'supplier': 'Carrier',
                        'terminal': 'T3',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'OSL',
                        'airport_name': 'Oslo Airport',
                        'event_id': 'rest_api-OSL-SGHA-2.8-DEICING-12',
                        'flight_number': 'SK421',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-06-24T09:00:00',
                        'period': '2026-06-24',
                        'source_type': 'rest_api',
                        'stand': '21',
                        'supplier': 'Carrier',
                        'terminal': 'T1',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'ARN',
                        'airport_name': 'Stockholm Arlanda Airport',
                        'event_id': 'rest_api-ARN-SGHA-2.8-DEICING-13',
                        'flight_number': 'SK422',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-07-08T09:00:00',
                        'period': '2026-07-08',
                        'source_type': 'rest_api',
                        'stand': '22',
                        'supplier': 'Carrier',
                        'terminal': 'T5',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'CPH',
                        'airport_name': 'Copenhagen Airport',
                        'event_id': 'rest_api-CPH-SGHA-2.8-DEICING-14',
                        'flight_number': 'SK423',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 17.31,
                        'observed_at': '2026-07-22T09:00:00',
                        'period': '2026-07-22',
                        'source_type': 'rest_api',
                        'stand': '23',
                        'supplier': 'Carrier',
                        'terminal': 'T3',
                        'unit': 'SEK per liter type II fluid'},
                    {   'airline_iata_code': 'SK',
                        'airline_name': 'SAS Scandinavian Airlines',
                        'airport_iata_code': 'OSL',
                        'airport_name': 'Oslo Airport',
                        'event_id': 'rest_api-OSL-SGHA-2.8-DEICING-15',
                        'flight_number': 'SK424',
                        'kpi_code': 'SGHA-2.8-DEICING',
                        'kpi_name': 'De-icing Fluid Charge',
                        'metric_value': 14.19,
                        'observed_at': '2026-08-05T09:00:00',
                        'period': '2026-08-05',
                        'source_type': 'rest_api',
                        'stand': '24',
                        'supplier': 'Carrier',
                        'terminal': 'T1',
                        'unit': 'SEK per liter type II fluid'}],
    'sap_s4hana': [   {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'ARN',
                          'airport_name': 'Stockholm Arlanda Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-ARN-SGHA-1.6-EXTRA-HOURS-01',
                          'flight_number': 'SK410',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-01-21',
                          'posting_date': '2026-01-21T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '10',
                          'supplier': 'Carrier',
                          'terminal': 'T5',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'CPH',
                          'airport_name': 'Copenhagen Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-CPH-SGHA-1.6-EXTRA-HOURS-02',
                          'flight_number': 'SK411',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-02-04',
                          'posting_date': '2026-02-04T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '11',
                          'supplier': 'Carrier',
                          'terminal': 'T3',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'OSL',
                          'airport_name': 'Oslo Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-OSL-SGHA-1.6-EXTRA-HOURS-03',
                          'flight_number': 'SK412',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-02-18',
                          'posting_date': '2026-02-18T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '12',
                          'supplier': 'Carrier',
                          'terminal': 'T1',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'ARN',
                          'airport_name': 'Stockholm Arlanda Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-ARN-SGHA-1.6-EXTRA-HOURS-04',
                          'flight_number': 'SK413',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-03-04',
                          'posting_date': '2026-03-04T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '13',
                          'supplier': 'Carrier',
                          'terminal': 'T5',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'CPH',
                          'airport_name': 'Copenhagen Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-CPH-SGHA-1.6-EXTRA-HOURS-05',
                          'flight_number': 'SK414',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-03-18',
                          'posting_date': '2026-03-18T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '14',
                          'supplier': 'Carrier',
                          'terminal': 'T3',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'OSL',
                          'airport_name': 'Oslo Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-OSL-SGHA-1.6-EXTRA-HOURS-06',
                          'flight_number': 'SK415',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-04-01',
                          'posting_date': '2026-04-01T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '15',
                          'supplier': 'Carrier',
                          'terminal': 'T1',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'ARN',
                          'airport_name': 'Stockholm Arlanda Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-ARN-SGHA-1.6-EXTRA-HOURS-07',
                          'flight_number': 'SK416',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-04-15',
                          'posting_date': '2026-04-15T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '16',
                          'supplier': 'Carrier',
                          'terminal': 'T5',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'CPH',
                          'airport_name': 'Copenhagen Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-CPH-SGHA-1.6-EXTRA-HOURS-08',
                          'flight_number': 'SK417',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-04-29',
                          'posting_date': '2026-04-29T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '17',
                          'supplier': 'Carrier',
                          'terminal': 'T3',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'OSL',
                          'airport_name': 'Oslo Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-OSL-SGHA-1.6-EXTRA-HOURS-09',
                          'flight_number': 'SK418',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-05-13',
                          'posting_date': '2026-05-13T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '18',
                          'supplier': 'Carrier',
                          'terminal': 'T1',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'ARN',
                          'airport_name': 'Stockholm Arlanda Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-ARN-SGHA-1.6-EXTRA-HOURS-10',
                          'flight_number': 'SK419',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-05-27',
                          'posting_date': '2026-05-27T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '19',
                          'supplier': 'Carrier',
                          'terminal': 'T5',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'CPH',
                          'airport_name': 'Copenhagen Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-CPH-SGHA-1.6-EXTRA-HOURS-11',
                          'flight_number': 'SK420',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-06-10',
                          'posting_date': '2026-06-10T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '20',
                          'supplier': 'Carrier',
                          'terminal': 'T3',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'OSL',
                          'airport_name': 'Oslo Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-OSL-SGHA-1.6-EXTRA-HOURS-12',
                          'flight_number': 'SK421',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-06-24',
                          'posting_date': '2026-06-24T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '21',
                          'supplier': 'Carrier',
                          'terminal': 'T1',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'ARN',
                          'airport_name': 'Stockholm Arlanda Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-ARN-SGHA-1.6-EXTRA-HOURS-13',
                          'flight_number': 'SK422',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-07-08',
                          'posting_date': '2026-07-08T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '22',
                          'supplier': 'Carrier',
                          'terminal': 'T5',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'CPH',
                          'airport_name': 'Copenhagen Airport',
                          'amount': 1244.0,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-CPH-SGHA-1.6-EXTRA-HOURS-14',
                          'flight_number': 'SK423',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-07-22',
                          'posting_date': '2026-07-22T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '23',
                          'supplier': 'Carrier',
                          'terminal': 'T3',
                          'unit': 'SEK per manhour'},
                      {   'airline_iata_code': 'SK',
                          'airline_name': 'SAS Scandinavian Airlines',
                          'airport_iata_code': 'OSL',
                          'airport_name': 'Oslo Airport',
                          'amount': 1020.08,
                          'company_code': 'SAS-ARN',
                          'document_id': 'sap_s4hana-OSL-SGHA-1.6-EXTRA-HOURS-15',
                          'flight_number': 'SK424',
                          'kpi_code': 'SGHA-1.6-EXTRA-HOURS',
                          'kpi_name': 'Extra Opening Hours',
                          'period': '2026-08-05',
                          'posting_date': '2026-08-05T09:00:00',
                          'source_type': 'sap_s4hana',
                          'stand': '24',
                          'supplier': 'Carrier',
                          'terminal': 'T1',
                          'unit': 'SEK per manhour'}],
    'scanned_images': [   {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.1-LANDING-01',
                              'flight_number': 'SK410',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-01-21',
                              'source_type': 'scanned_images',
                              'stand': '10',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-01-21T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.3-PASSENGER-01',
                              'flight_number': 'SK411',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-01-21',
                              'source_type': 'scanned_images',
                              'stand': '11',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-01-21T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.5-PARKING-01',
                              'flight_number': 'SK412',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-01-21',
                              'source_type': 'scanned_images',
                              'stand': '12',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-01-21T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.1-LANDING-02',
                              'flight_number': 'SK411',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-02-04',
                              'source_type': 'scanned_images',
                              'stand': '11',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-02-04T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.3-PASSENGER-02',
                              'flight_number': 'SK412',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-02-04',
                              'source_type': 'scanned_images',
                              'stand': '12',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-02-04T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.5-PARKING-02',
                              'flight_number': 'SK413',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-02-04',
                              'source_type': 'scanned_images',
                              'stand': '13',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-02-04T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.1-LANDING-03',
                              'flight_number': 'SK412',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-02-18',
                              'source_type': 'scanned_images',
                              'stand': '12',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-02-18T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.3-PASSENGER-03',
                              'flight_number': 'SK413',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-02-18',
                              'source_type': 'scanned_images',
                              'stand': '13',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-02-18T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.5-PARKING-03',
                              'flight_number': 'SK414',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-02-18',
                              'source_type': 'scanned_images',
                              'stand': '14',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-02-18T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.1-LANDING-04',
                              'flight_number': 'SK413',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-03-04',
                              'source_type': 'scanned_images',
                              'stand': '13',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-03-04T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.3-PASSENGER-04',
                              'flight_number': 'SK414',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-03-04',
                              'source_type': 'scanned_images',
                              'stand': '14',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-03-04T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.5-PARKING-04',
                              'flight_number': 'SK415',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-03-04',
                              'source_type': 'scanned_images',
                              'stand': '15',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-03-04T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.1-LANDING-05',
                              'flight_number': 'SK414',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-03-18',
                              'source_type': 'scanned_images',
                              'stand': '14',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-03-18T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.3-PASSENGER-05',
                              'flight_number': 'SK415',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-03-18',
                              'source_type': 'scanned_images',
                              'stand': '15',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-03-18T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.5-PARKING-05',
                              'flight_number': 'SK416',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-03-18',
                              'source_type': 'scanned_images',
                              'stand': '16',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-03-18T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.1-LANDING-06',
                              'flight_number': 'SK415',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-04-01',
                              'source_type': 'scanned_images',
                              'stand': '15',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-04-01T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.3-PASSENGER-06',
                              'flight_number': 'SK416',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-04-01',
                              'source_type': 'scanned_images',
                              'stand': '16',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-04-01T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.5-PARKING-06',
                              'flight_number': 'SK417',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-04-01',
                              'source_type': 'scanned_images',
                              'stand': '17',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-04-01T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.1-LANDING-07',
                              'flight_number': 'SK416',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-04-15',
                              'source_type': 'scanned_images',
                              'stand': '16',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-04-15T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.3-PASSENGER-07',
                              'flight_number': 'SK417',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-04-15',
                              'source_type': 'scanned_images',
                              'stand': '17',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-04-15T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.5-PARKING-07',
                              'flight_number': 'SK418',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-04-15',
                              'source_type': 'scanned_images',
                              'stand': '18',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-04-15T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.1-LANDING-08',
                              'flight_number': 'SK417',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-04-29',
                              'source_type': 'scanned_images',
                              'stand': '17',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-04-29T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.3-PASSENGER-08',
                              'flight_number': 'SK418',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-04-29',
                              'source_type': 'scanned_images',
                              'stand': '18',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-04-29T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.5-PARKING-08',
                              'flight_number': 'SK419',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-04-29',
                              'source_type': 'scanned_images',
                              'stand': '19',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-04-29T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.1-LANDING-09',
                              'flight_number': 'SK418',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-05-13',
                              'source_type': 'scanned_images',
                              'stand': '18',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-05-13T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.3-PASSENGER-09',
                              'flight_number': 'SK419',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-05-13',
                              'source_type': 'scanned_images',
                              'stand': '19',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-05-13T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.5-PARKING-09',
                              'flight_number': 'SK420',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-05-13',
                              'source_type': 'scanned_images',
                              'stand': '20',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-05-13T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.1-LANDING-10',
                              'flight_number': 'SK419',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-05-27',
                              'source_type': 'scanned_images',
                              'stand': '19',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-05-27T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.3-PASSENGER-10',
                              'flight_number': 'SK420',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-05-27',
                              'source_type': 'scanned_images',
                              'stand': '20',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-05-27T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.5-PARKING-10',
                              'flight_number': 'SK421',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-05-27',
                              'source_type': 'scanned_images',
                              'stand': '21',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-05-27T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.1-LANDING-11',
                              'flight_number': 'SK420',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-06-10',
                              'source_type': 'scanned_images',
                              'stand': '20',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-06-10T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.3-PASSENGER-11',
                              'flight_number': 'SK421',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-06-10',
                              'source_type': 'scanned_images',
                              'stand': '21',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-06-10T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.5-PARKING-11',
                              'flight_number': 'SK422',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-06-10',
                              'source_type': 'scanned_images',
                              'stand': '22',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-06-10T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.1-LANDING-12',
                              'flight_number': 'SK421',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-06-24',
                              'source_type': 'scanned_images',
                              'stand': '21',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-06-24T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.3-PASSENGER-12',
                              'flight_number': 'SK422',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-06-24',
                              'source_type': 'scanned_images',
                              'stand': '22',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-06-24T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.5-PARKING-12',
                              'flight_number': 'SK423',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-06-24',
                              'source_type': 'scanned_images',
                              'stand': '23',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-06-24T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.1-LANDING-13',
                              'flight_number': 'SK422',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-07-08',
                              'source_type': 'scanned_images',
                              'stand': '22',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-07-08T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.3-PASSENGER-13',
                              'flight_number': 'SK423',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-07-08',
                              'source_type': 'scanned_images',
                              'stand': '23',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-07-08T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'ARN',
                              'airport_name': 'Stockholm Arlanda Airport',
                              'event_id': 'scanned_images-ARN-SGHA-1.5-PARKING-13',
                              'flight_number': 'SK424',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-07-08',
                              'source_type': 'scanned_images',
                              'stand': '24',
                              'supplier': 'Carrier',
                              'terminal': 'T5',
                              'timestamp': '2026-07-08T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 77.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.1-LANDING-14',
                              'flight_number': 'SK423',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-07-22',
                              'source_type': 'scanned_images',
                              'stand': '23',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-07-22T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 141.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.3-PASSENGER-14',
                              'flight_number': 'SK424',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-07-22',
                              'source_type': 'scanned_images',
                              'stand': '24',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-07-22T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'CPH',
                              'airport_name': 'Copenhagen Airport',
                              'event_id': 'scanned_images-CPH-SGHA-1.5-PARKING-14',
                              'flight_number': 'SK425',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-07-22',
                              'source_type': 'scanned_images',
                              'stand': '25',
                              'supplier': 'Carrier',
                              'terminal': 'T3',
                              'timestamp': '2026-07-22T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'},
                          {   'actual_value': 63.14,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.1-LANDING-15',
                              'flight_number': 'SK424',
                              'kpi_code': 'SGHA-1.1-LANDING',
                              'kpi_name': 'Landing Charge',
                              'period': '2026-08-05',
                              'source_type': 'scanned_images',
                              'stand': '24',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-08-05T09:00:00',
                              'unit': 'SEK per tonne'},
                          {   'actual_value': 115.62,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.3-PASSENGER-15',
                              'flight_number': 'SK425',
                              'kpi_code': 'SGHA-1.3-PASSENGER',
                              'kpi_name': 'Passenger Charge',
                              'period': '2026-08-05',
                              'source_type': 'scanned_images',
                              'stand': '25',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-08-05T09:00:00',
                              'unit': 'SEK per departing passenger'},
                          {   'actual_value': 32.0,
                              'airline_iata_code': 'SK',
                              'airline_name': 'SAS Scandinavian Airlines',
                              'airport_iata_code': 'OSL',
                              'airport_name': 'Oslo Airport',
                              'event_id': 'scanned_images-OSL-SGHA-1.5-PARKING-15',
                              'flight_number': 'SK426',
                              'kpi_code': 'SGHA-1.5-PARKING',
                              'kpi_name': 'Apron Parking Charge',
                              'period': '2026-08-05',
                              'source_type': 'scanned_images',
                              'stand': '26',
                              'supplier': 'Carrier',
                              'terminal': 'T1',
                              'timestamp': '2026-08-05T09:00:00',
                              'unit': 'SEK per MTOW tonne-day'}]}