version: '3.8'

services:
  frontend:
    image: nextjs-frontend:dev
    container_name: frontend-dev
    ports:
      - "4200:4200"
    env_file:
      - ./apps/frontend/.env.dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - .:/app
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge