"""renewal_advice tool (P5.3 / docs/30 Wave H.3)"""
from __future__ import annotations
import logging, httpx
from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field
from ..config import settings

log = logging.getLogger(__name__)


class RenewalAdviceArgs(BaseModel):
    contract_id: str | None = Field(
        None,
        description=(
            "Target a single contract's cached renewal advice. Omit to "
            "get the portfolio view — every contract expiring within "
            "lead_days days, with per-contract advice and portfolio "
            "recommendation counts (renew / renegotiate / let_expire / pause)."
        ),
    )
    lead_days: int = Field(
        90, ge=1, le=365,
        description="Window size for the portfolio view. Defaults to 90 — the CLM industry-standard renewal lookahead.",
    )
    limit: int = Field(20, ge=1, le=50)


def build_renewal_advice(org_id: str) -> StructuredTool:
    async def _arun(contract_id=None, lead_days: int = 90, limit: int = 20) -> str:
        url = f"{settings.api_url.rstrip('/')}/api/internal/ai/tools/renewal_advice"
        headers = {"x-internal-secret": settings.internal_service_secret, "x-internal-service": "agents", "content-type": "application/json"}
        payload: dict = {"orgId": org_id, "leadDays": lead_days, "limit": limit}
        if contract_id: payload["contractId"] = contract_id
        async with httpx.AsyncClient(timeout=httpx.Timeout(12.0)) as client:
            r = await client.post(url, json=payload, headers=headers)
        if r.status_code >= 400:
            log.warning("[renewal_advice] Node %s: %s", r.status_code, r.text[:200])
            return '{"error":"renewal_advice_failed","status":' + str(r.status_code) + "}"
        return r.text

    def _run(contract_id=None, lead_days: int = 90, limit: int = 20):
        import asyncio
        return asyncio.run(_arun(contract_id, lead_days, limit))

    return StructuredTool.from_function(
        coroutine=_arun, func=_run, name="renewal_advice",
        description=(
            "Read cached renewal recommendations generated by the "
            "renewal advisor. With contract_id, returns that contract's "
            "advice (recommendation + rationale + negotiationPoints + "
            "riskFlags + decision). Without it, returns every contract "
            "expiring in the next `lead_days` days (default 90) plus "
            "portfolio-level recommendation counts. Use ONLY when the "
            "user is asking about renewal/expiry timing — e.g. 'what "
            "should we do about the Acme renewal?', 'which contracts "
            "renew this quarter?', or 'summarise our upcoming renewals'. "
            "DO NOT use for general 'find/list/show me' queries that "
            "happen to mention a cohort or matter — those need "
            "contract_search or matter_list. Persona-test fix #4: this "
            "tool was hijacking 'show me contracts in the Memphis hub "
            "cohort' (which is a matter query, not a renewal query). "
            "READ-ONLY — to generate a fresh LLM advice the user must "
            "click the 'Get renewal advice' button in the rail."
        ),
        args_schema=RenewalAdviceArgs,
    )
