/**
 * Universal clause library — 106 clauses across the 18 universal categories.
 *
 * Content is plain HTML (matches `ClauseLibraryItem.content` column). Each
 * clause is a short, reusable building-block — not a full agreement. Most
 * clauses are tagged `standard`; common buy-side preferred wording is tagged
 * `favorable`; common sell-side preferred wording is tagged `unfavorable`.
 *
 * Variable placeholders use {{tokenName}} format — the existing template
 * renderer resolves them from `Template.variables`.
 *
 * Re-running the seed is safe: existing clauses (matched by orgId + title)
 * are skipped, not duplicated.
 */

export interface SeedClause {
  categorySlug: string
  title: string
  content: string
  tags: string[]
  riskRating: 'favorable' | 'unfavorable' | 'neutral' | 'standard'
  isApproved: boolean
}

export const UNIVERSAL_CLAUSES: SeedClause[] = [
  // ─── Definitions & Interpretation ───────────────────────────────────────
  {
    categorySlug: 'definitions',
    title: 'Standard Defined Terms',
    content: `<p>Capitalized terms used in this Agreement have the meanings given in this Section or where first defined in the body of this Agreement. References to "including" and similar terms are illustrative and not limiting. The headings are for convenience only and do not affect interpretation.</p>`,
    tags: ['definitions', 'interpretation'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'definitions',
    title: 'Order of Precedence',
    content: `<p>In the event of any conflict between the documents comprising this Agreement, the following order of precedence applies, in descending order: (a) any signed amendment; (b) the body of this Agreement; (c) the applicable Statement of Work or Order Form; and (d) any exhibits or schedules. No purchase order, vendor terms, or pre-printed terms in any ordering document apply, even if signed.</p>`,
    tags: ['precedence', 'conflict', 'interpretation'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'definitions',
    title: 'Affiliate Definition',
    content: `<p>"Affiliate" means, with respect to a party, any entity that directly or indirectly controls, is controlled by, or is under common control with such party, where "control" means ownership of more than fifty percent (50%) of the voting securities or equivalent ownership interests.</p>`,
    tags: ['affiliate', 'definition'],
    riskRating: 'standard',
    isApproved: true,
  },

  // ─── Scope of Services ──────────────────────────────────────────────────
  {
    categorySlug: 'scope-services',
    title: 'Services Description (SOW-Based)',
    content: `<p>Provider will perform the professional services ("Services") described in one or more Statements of Work ("SOWs") executed by the parties. Each SOW will reference this Agreement and specify the scope, deliverables, timeline, fees, and any project-specific terms.</p>`,
    tags: ['services', 'sow', 'scope'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'scope-services',
    title: 'Acceptance of Deliverables',
    content: `<p>Customer will review each Deliverable within {{acceptancePeriod}} business days of delivery. Customer will either accept the Deliverable in writing or provide written notice of material non-conformity with the acceptance criteria set forth in the applicable SOW. If Customer does not respond within the review period, the Deliverable will be deemed accepted.</p>`,
    tags: ['acceptance', 'deliverables', 'sow'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'scope-services',
    title: 'Change Control',
    content: `<p>Any change to a SOW's scope, deliverables, schedule, or fees requires a written change order signed by an authorized representative of each party. Provider is not obligated to perform out-of-scope work without an executed change order.</p>`,
    tags: ['change-control', 'scope', 'sow'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'scope-services',
    title: 'Customer Responsibilities',
    content: `<p>Customer will provide Provider with timely access to the personnel, systems, information, and decisions reasonably required for Provider to perform the Services. Provider's performance is dependent on Customer's cooperation, and Provider is not responsible for delays caused by Customer's failure to perform its obligations.</p>`,
    tags: ['customer-responsibilities', 'cooperation'],
    riskRating: 'unfavorable',
    isApproved: true,
  },
  {
    categorySlug: 'scope-services',
    title: 'Subcontractors',
    content: `<p>Provider may engage subcontractors to perform any portion of the Services, provided that Provider remains responsible for the acts and omissions of its subcontractors and for ensuring that its subcontractors are bound by obligations no less protective than those in this Agreement.</p>`,
    tags: ['subcontractors', 'delegation'],
    riskRating: 'neutral',
    isApproved: true,
  },

  // ─── Fees & Payment ─────────────────────────────────────────────────────
  {
    categorySlug: 'fees-payment',
    title: 'Fees and Payment Terms — Net 30',
    content: `<p>Customer will pay all undisputed fees set forth in each SOW within thirty (30) days of receipt of Provider's invoice. All amounts are stated in {{currency}} and are non-refundable except as expressly set forth in this Agreement.</p>`,
    tags: ['payment', 'invoicing', 'net-30'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'fees-payment',
    title: 'Fees and Payment Terms — Net 60',
    content: `<p>Customer will pay all undisputed fees set forth in each SOW within sixty (60) days of receipt of Provider's invoice. All amounts are stated in {{currency}}.</p>`,
    tags: ['payment', 'invoicing', 'net-60'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'fees-payment',
    title: 'Taxes',
    content: `<p>Fees are exclusive of all taxes. Customer is responsible for all sales, use, value-added, and similar taxes assessed on the Services, except taxes based on Provider's net income. If Provider is required to collect such taxes, Provider will include them as a separate line item on its invoices.</p>`,
    tags: ['taxes', 'vat', 'sales-tax'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'fees-payment',
    title: 'Late Payment Interest',
    content: `<p>Undisputed amounts not paid when due will accrue interest at the lesser of one percent (1%) per month or the maximum rate permitted by law, calculated from the original due date until paid in full.</p>`,
    tags: ['late-payment', 'interest'],
    riskRating: 'neutral',
    isApproved: true,
  },
  {
    categorySlug: 'fees-payment',
    title: 'Disputed Charges',
    content: `<p>If Customer in good faith disputes any portion of an invoice, Customer will notify Provider in writing within fifteen (15) days of receipt, identifying the disputed amount and the basis for the dispute. Customer will pay all undisputed amounts and the parties will work in good faith to resolve the dispute within thirty (30) days.</p>`,
    tags: ['disputed-charges', 'invoicing'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'fees-payment',
    title: 'Expenses',
    content: `<p>Customer will reimburse Provider for reasonable, documented travel and out-of-pocket expenses incurred in connection with the Services, provided that any expenses exceeding {{expenseApprovalThreshold}} require Customer's prior written approval. Provider will provide receipts upon request.</p>`,
    tags: ['expenses', 'reimbursement', 'travel'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'fees-payment',
    title: 'Price Escalation Cap',
    content: `<p>Provider may increase its fees no more than once per twelve (12) month period and by no more than the greater of three percent (3%) or the percentage change in the Consumer Price Index for the prior twelve-month period. Any such increase requires sixty (60) days' prior written notice to Customer.</p>`,
    tags: ['price-escalation', 'cpi', 'renewal'],
    riskRating: 'favorable',
    isApproved: true,
  },

  // ─── Term & Termination ─────────────────────────────────────────────────
  {
    categorySlug: 'term-termination',
    title: 'Initial Term and Auto-Renewal',
    content: `<p>This Agreement commences on the Effective Date and continues for an initial term of {{initialTerm}} years (the "Initial Term"). Thereafter, the Agreement will automatically renew for successive one (1) year periods (each, a "Renewal Term") unless either party provides written notice of non-renewal at least {{nonRenewalNoticeDays}} days before the end of the then-current term.</p>`,
    tags: ['term', 'auto-renewal', 'non-renewal'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'term-termination',
    title: 'Termination for Convenience',
    content: `<p>Either party may terminate this Agreement for any reason or no reason upon at least {{terminationForConvenienceDays}} days' prior written notice to the other party. Termination for convenience does not relieve Customer of its obligation to pay for Services performed before the effective date of termination.</p>`,
    tags: ['termination', 'convenience'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'term-termination',
    title: 'Termination for Cause — Material Breach',
    content: `<p>Either party may terminate this Agreement if the other party materially breaches the Agreement and fails to cure the breach within thirty (30) days after receiving written notice describing the breach in reasonable detail. For breaches incapable of cure (such as a breach of confidentiality), termination is effective upon the breaching party's receipt of notice.</p>`,
    tags: ['termination', 'cause', 'material-breach', 'cure'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'term-termination',
    title: 'Termination for Insolvency',
    content: `<p>Either party may terminate this Agreement immediately upon written notice if the other party (a) files or has filed against it a petition in bankruptcy, (b) makes a general assignment for the benefit of creditors, (c) has a receiver, trustee, or similar officer appointed for its assets, or (d) ceases to do business in the ordinary course.</p>`,
    tags: ['termination', 'insolvency', 'bankruptcy'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'term-termination',
    title: 'Effect of Termination',
    content: `<p>Upon termination or expiration of this Agreement: (a) all licenses and rights granted to Customer terminate; (b) each party will return or destroy the other party's Confidential Information; (c) Customer will pay Provider for all Services performed through the effective date of termination; and (d) those provisions that by their nature survive termination (including confidentiality, IP, indemnification, limitation of liability, and governing law) will survive.</p>`,
    tags: ['termination', 'effect', 'survival'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'term-termination',
    title: 'Refund on Termination for Cause',
    content: `<p>If Customer terminates this Agreement for Provider's uncured material breach, Provider will refund any prepaid, unused fees on a pro-rata basis within thirty (30) days of the effective date of termination.</p>`,
    tags: ['termination', 'refund', 'cause'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'term-termination',
    title: 'Transition Assistance',
    content: `<p>Upon expiration or termination of this Agreement for any reason, Provider will, at Customer's request, provide reasonable transition assistance for up to ninety (90) days at Provider's then-current professional services rates, to facilitate an orderly migration of Customer's data and operations to Customer or a successor provider.</p>`,
    tags: ['transition', 'wind-down', 'termination'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'term-termination',
    title: 'No Termination for Convenience (Vendor-Favorable)',
    content: `<p>Neither party may terminate this Agreement for convenience during the Initial Term. Termination during the Initial Term is permitted only for the other party's uncured material breach as set forth in this Agreement.</p>`,
    tags: ['termination', 'no-convenience'],
    riskRating: 'unfavorable',
    isApproved: false,
  },

  // ─── Confidentiality ────────────────────────────────────────────────────
  {
    categorySlug: 'confidentiality',
    title: 'Definition of Confidential Information',
    content: `<p>"Confidential Information" means any non-public information disclosed by one party (the "Discloser") to the other party (the "Recipient"), in any form, that is identified as confidential or that a reasonable person would understand to be confidential given the nature of the information and the circumstances of disclosure. Confidential Information includes business plans, pricing, customer lists, technical data, source code, product designs, and personal data.</p>`,
    tags: ['confidentiality', 'definition'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'confidentiality',
    title: 'Confidentiality Obligations',
    content: `<p>The Recipient will (a) use the Confidential Information solely to perform its obligations or exercise its rights under this Agreement; (b) protect the Confidential Information using at least the same degree of care it uses for its own confidential information of similar importance, but no less than a reasonable degree of care; and (c) limit access to the Confidential Information to its employees, contractors, and advisors who have a need to know and who are bound by written obligations of confidentiality no less protective than this Section.</p>`,
    tags: ['confidentiality', 'obligations'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'confidentiality',
    title: 'Confidentiality Exclusions',
    content: `<p>The obligations of confidentiality do not apply to information that the Recipient can demonstrate: (a) was already in the Recipient's lawful possession without confidentiality obligations before disclosure; (b) is or becomes publicly available through no fault of the Recipient; (c) is rightfully received from a third party without confidentiality obligations; or (d) is independently developed by the Recipient without use of or reference to the Discloser's Confidential Information.</p>`,
    tags: ['confidentiality', 'exclusions'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'confidentiality',
    title: 'Compelled Disclosure',
    content: `<p>If the Recipient is compelled by law, court order, or governmental authority to disclose any Confidential Information, the Recipient will, to the extent legally permitted, promptly notify the Discloser so that the Discloser may seek a protective order or other appropriate remedy, and the Recipient will disclose only that portion of the Confidential Information that is legally required.</p>`,
    tags: ['confidentiality', 'compelled-disclosure', 'subpoena'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'confidentiality',
    title: 'Return or Destruction of Confidential Information',
    content: `<p>Upon termination of this Agreement or the Discloser's written request, the Recipient will promptly return or destroy all Confidential Information in its possession (including all copies and derivatives) and, upon request, certify such return or destruction in writing. The Recipient may retain Confidential Information to the extent required by law or its automatic backup systems, provided that such retained information remains subject to the confidentiality obligations.</p>`,
    tags: ['confidentiality', 'return', 'destruction'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'confidentiality',
    title: 'Confidentiality Term — Indefinite for Trade Secrets',
    content: `<p>The obligations of confidentiality under this Agreement will continue for a period of five (5) years from the date of disclosure, or, with respect to trade secrets, for so long as the information remains a trade secret under applicable law.</p>`,
    tags: ['confidentiality', 'term', 'trade-secrets'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'confidentiality',
    title: 'Confidentiality Term — 3 Years',
    content: `<p>The obligations of confidentiality under this Agreement will continue for three (3) years from the date of disclosure.</p>`,
    tags: ['confidentiality', 'term', '3-years'],
    riskRating: 'unfavorable',
    isApproved: false,
  },

  // ─── Intellectual Property ──────────────────────────────────────────────
  {
    categorySlug: 'ip-ownership',
    title: 'Background IP',
    content: `<p>Each party retains all right, title, and interest in and to its Background Intellectual Property. "Background Intellectual Property" means all intellectual property owned or controlled by a party as of the Effective Date or developed independently outside the scope of this Agreement.</p>`,
    tags: ['ip', 'background-ip', 'ownership'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'ip-ownership',
    title: 'Work Product Assignment to Customer',
    content: `<p>All deliverables and work product created by Provider specifically for Customer under this Agreement (excluding Background IP and generally applicable Provider tools and methodologies) ("Work Product") are works made for hire under the U.S. Copyright Act and will be the sole and exclusive property of Customer upon payment in full. To the extent any Work Product is not a work made for hire, Provider hereby irrevocably assigns to Customer all right, title, and interest in and to the Work Product.</p>`,
    tags: ['ip', 'work-product', 'assignment', 'work-for-hire'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'ip-ownership',
    title: 'Customer License — SaaS Services',
    content: `<p>Subject to Customer's payment of fees and compliance with this Agreement, Provider grants Customer a worldwide, non-exclusive, non-transferable license during the Term to access and use the Services solely for Customer's internal business purposes.</p>`,
    tags: ['ip', 'license', 'saas'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'ip-ownership',
    title: 'Provider License to Use Customer Data',
    content: `<p>Customer grants Provider a limited, non-exclusive, non-transferable license to access and use Customer Data solely to provide and improve the Services to Customer and as otherwise expressly permitted in this Agreement. Customer retains all right, title, and interest in and to Customer Data.</p>`,
    tags: ['ip', 'customer-data', 'license'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'ip-ownership',
    title: 'Feedback License',
    content: `<p>If Customer provides Provider with suggestions, ideas, or feedback regarding the Services ("Feedback"), Customer grants Provider a perpetual, irrevocable, royalty-free, worldwide license to use the Feedback for any purpose, without compensation or attribution to Customer.</p>`,
    tags: ['ip', 'feedback'],
    riskRating: 'unfavorable',
    isApproved: true,
  },
  {
    categorySlug: 'ip-ownership',
    title: 'Open Source Software',
    content: `<p>Provider will identify, in documentation made available to Customer, all open source software components included in the Services, the applicable license for each, and any source code obligations. Provider will not include any open source software whose license imposes obligations that would require Customer to disclose or license its proprietary code (sometimes referred to as "copyleft" or "viral" licenses).</p>`,
    tags: ['ip', 'open-source', 'oss'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'ip-ownership',
    title: 'Trademark License',
    content: `<p>Neither party may use the other party's name, logo, or trademarks without prior written consent, except that each party may identify the other as a customer or vendor in standard customer/vendor lists and case studies, subject to the other party's reasonable review of any specific marketing content.</p>`,
    tags: ['ip', 'trademark', 'logo'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'ip-ownership',
    title: 'Residual Knowledge',
    content: `<p>Subject to the confidentiality obligations, nothing in this Agreement restricts a Recipient's personnel from using the general knowledge, skills, and experience retained in their unaided memory after performing the Services, provided that such use does not involve the deliberate retention or disclosure of the Discloser's Confidential Information.</p>`,
    tags: ['ip', 'residuals', 'knowledge'],
    riskRating: 'unfavorable',
    isApproved: true,
  },

  // ─── Data Protection & Privacy ──────────────────────────────────────────
  {
    categorySlug: 'data-privacy',
    title: 'Data Processing — DPA Reference',
    content: `<p>To the extent Provider processes Personal Data on behalf of Customer in connection with the Services, the parties will execute and comply with the Data Processing Addendum attached as Exhibit {{dpaExhibit}}, which is incorporated into and forms part of this Agreement. The DPA prevails over conflicting terms in this Agreement as to Personal Data.</p>`,
    tags: ['data-protection', 'dpa', 'gdpr', 'ccpa'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'data-privacy',
    title: 'Personal Data — Definition and Roles',
    content: `<p>"Personal Data" has the meaning given in applicable Data Protection Laws (including GDPR and CCPA/CPRA). With respect to Personal Data of Customer's end users processed in connection with the Services, Customer is the Controller (or Business) and Provider is the Processor (or Service Provider).</p>`,
    tags: ['data-protection', 'personal-data', 'controller', 'processor'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'data-privacy',
    title: 'Sub-Processors',
    content: `<p>Customer authorizes Provider to engage sub-processors to assist in providing the Services, provided that Provider (a) maintains a current list of sub-processors and makes it available to Customer; (b) imposes data protection obligations on each sub-processor that are at least as protective as those in the DPA; and (c) remains liable for the acts and omissions of its sub-processors. Provider will provide at least thirty (30) days' notice of any new sub-processor and Customer may object on reasonable data protection grounds.</p>`,
    tags: ['data-protection', 'sub-processors'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'data-privacy',
    title: 'Cross-Border Data Transfers',
    content: `<p>Where Provider transfers Personal Data outside the jurisdiction of origin, Provider will rely on a valid transfer mechanism under applicable Data Protection Laws (including the Standard Contractual Clauses or an applicable adequacy decision) and will implement supplementary measures as required.</p>`,
    tags: ['data-protection', 'cross-border', 'sccs', 'transfer'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'data-privacy',
    title: 'Security Incident Notification',
    content: `<p>Provider will notify Customer of any actual or reasonably suspected Security Incident affecting Personal Data without undue delay and in any event within seventy-two (72) hours of becoming aware of the Security Incident. The notification will include the information reasonably required to enable Customer to meet its own notification obligations.</p>`,
    tags: ['data-protection', 'breach-notification', '72-hours'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'data-privacy',
    title: 'Data Subject Requests',
    content: `<p>Provider will, taking into account the nature of the processing, reasonably assist Customer in responding to requests by data subjects to exercise their rights under applicable Data Protection Laws (including access, rectification, erasure, restriction, portability, and objection), at no additional charge for reasonable assistance during the Term.</p>`,
    tags: ['data-protection', 'dsr', 'data-subjects'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'data-privacy',
    title: 'Return or Deletion of Personal Data',
    content: `<p>Upon termination of the Services, Provider will, at Customer's choice, return all Personal Data to Customer or delete the Personal Data, and delete existing copies, within thirty (30) days, unless retention is required by applicable law. Provider will confirm such return or deletion in writing upon request.</p>`,
    tags: ['data-protection', 'return', 'deletion'],
    riskRating: 'standard',
    isApproved: true,
  },

  // ─── Information Security ───────────────────────────────────────────────
  {
    categorySlug: 'security',
    title: 'Security Standards — SOC 2 / ISO 27001',
    content: `<p>Provider will implement and maintain administrative, technical, and physical safeguards designed to protect the confidentiality, integrity, and availability of Customer Data, in accordance with industry-standard frameworks such as SOC 2 Type II and ISO/IEC 27001:2022. Provider will maintain such certifications during the Term and make summary reports available to Customer upon reasonable request.</p>`,
    tags: ['security', 'soc2', 'iso27001'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'security',
    title: 'Encryption',
    content: `<p>Provider will encrypt Customer Data (a) in transit using industry-standard protocols (e.g., TLS 1.2 or higher) and (b) at rest using industry-standard encryption (e.g., AES-256). Provider will protect encryption keys against unauthorized access.</p>`,
    tags: ['security', 'encryption', 'tls', 'aes'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'security',
    title: 'Access Controls',
    content: `<p>Provider will limit access to Customer Data to personnel with a need to know, will require multi-factor authentication for all administrative access, and will promptly revoke access upon role change or termination.</p>`,
    tags: ['security', 'access-control', 'mfa'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'security',
    title: 'Penetration Testing',
    content: `<p>Provider will conduct, or cause to be conducted by a qualified independent firm, penetration testing of the Services at least annually. Provider will provide Customer with a summary of the most recent test results and remediation status upon reasonable request, subject to confidentiality obligations.</p>`,
    tags: ['security', 'pen-test', 'vulnerability'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'security',
    title: 'Customer Audit Rights',
    content: `<p>No more than once per year (and additionally following a Security Incident affecting Customer Data), Customer may, at its own expense and upon thirty (30) days' prior written notice, audit Provider's compliance with the security obligations in this Agreement, during normal business hours and in a manner that does not unreasonably interfere with Provider's operations. The parties may agree to substitute audit reports from independent auditors in lieu of an on-site audit.</p>`,
    tags: ['security', 'audit'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'security',
    title: 'Background Checks',
    content: `<p>Provider will conduct background checks (including criminal history checks where lawful) on personnel who will have access to Customer Data, to the extent permitted by applicable law.</p>`,
    tags: ['security', 'background-check', 'personnel'],
    riskRating: 'standard',
    isApproved: true,
  },

  // ─── Representations & Warranties ───────────────────────────────────────
  {
    categorySlug: 'warranties',
    title: 'Mutual Representations',
    content: `<p>Each party represents and warrants that (a) it has the full corporate power and authority to enter into and perform this Agreement; (b) its execution and performance of this Agreement do not and will not conflict with any other obligation; and (c) it will comply with all laws and regulations applicable to its performance under this Agreement.</p>`,
    tags: ['warranties', 'authority', 'compliance'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'warranties',
    title: 'Services Warranty — Professional Manner',
    content: `<p>Provider warrants that the Services will be performed in a professional and workmanlike manner consistent with generally accepted industry standards and the specifications in the applicable SOW. Customer must report any breach of this warranty in writing within thirty (30) days of the relevant Services. Provider's sole obligation, and Customer's sole remedy, for breach of this warranty is for Provider to re-perform the non-conforming Services.</p>`,
    tags: ['warranties', 'services', 'workmanlike'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'warranties',
    title: 'No-Malicious-Code Warranty',
    content: `<p>Provider warrants that the Services and any software provided as part of the Services will not contain viruses, worms, trojan horses, time bombs, or other malicious code intended to harm Customer's systems or data.</p>`,
    tags: ['warranties', 'malware', 'security'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'warranties',
    title: 'Non-Infringement Warranty',
    content: `<p>Provider warrants that the Services and any Provider-provided materials, when used as permitted by this Agreement, will not infringe or misappropriate any third party's intellectual property rights.</p>`,
    tags: ['warranties', 'non-infringement', 'ip'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'warranties',
    title: 'Warranty Disclaimer',
    content: `<p>EXCEPT FOR THE EXPRESS WARRANTIES IN THIS AGREEMENT, THE SERVICES ARE PROVIDED "AS IS" AND PROVIDER DISCLAIMS ALL OTHER WARRANTIES, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. PROVIDER DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE.</p>`,
    tags: ['warranties', 'disclaimer', 'as-is'],
    riskRating: 'unfavorable',
    isApproved: true,
  },
  {
    categorySlug: 'warranties',
    title: 'Anti-Corruption Warranty',
    content: `<p>Each party warrants that it will comply with all applicable anti-bribery and anti-corruption laws (including the U.S. Foreign Corrupt Practices Act and the UK Bribery Act) and will not, directly or indirectly, offer or pay anything of value to any government official or other person to obtain or retain business.</p>`,
    tags: ['warranties', 'anti-corruption', 'fcpa', 'bribery'],
    riskRating: 'standard',
    isApproved: true,
  },

  // ─── Indemnification ────────────────────────────────────────────────────
  {
    categorySlug: 'indemnification',
    title: 'IP Indemnification by Provider',
    content: `<p>Provider will defend Customer against any third-party claim that the Services, when used as permitted by this Agreement, infringe or misappropriate the third party's intellectual property rights, and will indemnify Customer against all damages and costs (including reasonable attorneys' fees) finally awarded against Customer or agreed in settlement.</p>`,
    tags: ['indemnification', 'ip', 'infringement'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'indemnification',
    title: 'IP Indemnification — Provider Remedies',
    content: `<p>If the Services are, or in Provider's reasonable opinion are likely to become, the subject of an IP infringement claim, Provider may, at its option and expense: (a) procure for Customer the right to continue using the affected portion of the Services; (b) modify the affected portion to be non-infringing while preserving substantially equivalent functionality; or (c) if neither (a) nor (b) is commercially reasonable, terminate the affected portion of the Services and refund any prepaid, unused fees on a pro-rata basis.</p>`,
    tags: ['indemnification', 'ip', 'remedies'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'indemnification',
    title: 'IP Indemnification Exclusions',
    content: `<p>Provider has no obligation under the IP indemnity for claims arising from: (a) use of the Services in combination with any product, service, or data not provided by Provider, where the claim would have been avoided without such combination; (b) modification of the Services by anyone other than Provider; (c) use of the Services in a manner not authorized by the Documentation; or (d) Customer Data.</p>`,
    tags: ['indemnification', 'ip', 'exclusions'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'indemnification',
    title: 'Mutual Indemnification — Third-Party Bodily Injury / Property Damage',
    content: `<p>Each party will defend and indemnify the other party against third-party claims for bodily injury or tangible property damage to the extent caused by the indemnifying party's gross negligence or willful misconduct, and will pay any damages and costs finally awarded against the indemnified party or agreed in settlement.</p>`,
    tags: ['indemnification', 'bodily-injury', 'property-damage'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'indemnification',
    title: 'Indemnification Procedure',
    content: `<p>The indemnified party will (a) promptly notify the indemnifying party of any claim subject to indemnification; (b) give the indemnifying party sole control of the defense and settlement of the claim, provided that no settlement that imposes any obligation or admission of liability on the indemnified party may be agreed without the indemnified party's prior written consent (not to be unreasonably withheld); and (c) provide reasonable cooperation in the defense at the indemnifying party's expense.</p>`,
    tags: ['indemnification', 'procedure'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'indemnification',
    title: 'Customer Indemnification — Customer Data',
    content: `<p>Customer will defend Provider against any third-party claim arising from (a) Customer Data, including any allegation that Customer Data infringes a third party's rights, or (b) Customer's use of the Services in violation of this Agreement or applicable law, and will indemnify Provider against all damages and costs finally awarded against Provider or agreed in settlement.</p>`,
    tags: ['indemnification', 'customer-data'],
    riskRating: 'unfavorable',
    isApproved: true,
  },

  // ─── Limitation of Liability ────────────────────────────────────────────
  {
    categorySlug: 'liability',
    title: 'Liability Cap — 12 Months Fees',
    content: `<p>EXCEPT FOR THE EXCLUDED CLAIMS (DEFINED BELOW), EACH PARTY'S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THIS AGREEMENT, REGARDLESS OF THE FORM OF ACTION, WILL NOT EXCEED THE FEES PAID OR PAYABLE BY CUSTOMER TO PROVIDER UNDER THIS AGREEMENT IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM.</p>`,
    tags: ['liability', 'cap', '12-months'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'liability',
    title: 'Liability Cap — 24 Months Fees',
    content: `<p>EXCEPT FOR THE EXCLUDED CLAIMS, EACH PARTY'S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THIS AGREEMENT WILL NOT EXCEED TWO TIMES THE FEES PAID OR PAYABLE BY CUSTOMER TO PROVIDER UNDER THIS AGREEMENT IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM.</p>`,
    tags: ['liability', 'cap', '24-months', 'super-cap'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'liability',
    title: 'Consequential Damages Exclusion',
    content: `<p>EXCEPT FOR THE EXCLUDED CLAIMS, NEITHER PARTY WILL BE LIABLE FOR ANY LOST PROFITS, LOST REVENUES, LOSS OF DATA, LOSS OF GOODWILL, OR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND REGARDLESS OF WHETHER THE CLAIM IS BASED ON CONTRACT, TORT, OR OTHER LEGAL THEORY.</p>`,
    tags: ['liability', 'consequential', 'indirect'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'liability',
    title: 'Excluded Claims (Carve-Outs)',
    content: `<p>The limitations of liability do not apply to: (a) a party's indemnification obligations; (b) breach of confidentiality obligations; (c) infringement or misappropriation of the other party's intellectual property; (d) Customer's payment obligations; (e) a party's gross negligence or willful misconduct; and (f) liability that cannot be limited under applicable law.</p>`,
    tags: ['liability', 'carve-out', 'excluded-claims'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'liability',
    title: 'Super-Cap for Data Breach',
    content: `<p>Notwithstanding the general liability cap, Provider's aggregate liability arising from a Security Incident or breach of the DPA will not exceed three times (3x) the fees paid or payable by Customer to Provider under this Agreement in the twelve (12) months preceding the event giving rise to the claim.</p>`,
    tags: ['liability', 'super-cap', 'data-breach', 'security'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'liability',
    title: 'Basis of the Bargain',
    content: `<p>The parties acknowledge that the limitations of liability in this Agreement reflect the allocation of risk between the parties and form an essential basis of the bargain, and will apply notwithstanding the failure of any limited remedy of its essential purpose.</p>`,
    tags: ['liability', 'basis-of-bargain'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'liability',
    title: 'Unlimited Liability for Gross Negligence Only',
    content: `<p>Notwithstanding any other provision of this Agreement, neither party limits its liability for death or personal injury caused by its negligence, fraud or fraudulent misrepresentation, or any other liability that cannot be limited under applicable law.</p>`,
    tags: ['liability', 'unlimited', 'gross-negligence'],
    riskRating: 'standard',
    isApproved: true,
  },

  // ─── Insurance ──────────────────────────────────────────────────────────
  {
    categorySlug: 'insurance',
    title: 'Required Insurance Coverages',
    content: `<p>During the Term and for two (2) years thereafter, Provider will maintain, at its own expense, the following insurance coverages with insurers having an A.M. Best rating of A- or better: (a) Commercial General Liability — not less than {{cglLimit}}; (b) Cyber/Technology Errors & Omissions — not less than {{cyberLimit}}; (c) Workers' Compensation — at statutory limits; and (d) Employer's Liability — not less than {{eplLimit}}.</p>`,
    tags: ['insurance', 'coverages', 'cyber'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'insurance',
    title: 'Certificates of Insurance',
    content: `<p>Provider will furnish Customer with certificates of insurance evidencing the required coverages upon request and at least annually. Customer will be named as additional insured on the Commercial General Liability policy with respect to liability arising from Provider's performance under this Agreement.</p>`,
    tags: ['insurance', 'coi', 'additional-insured'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'insurance',
    title: 'Waiver of Subrogation',
    content: `<p>Each party waives, and will cause its insurers to waive, all rights of subrogation against the other party with respect to losses covered by the insurance maintained under this Agreement.</p>`,
    tags: ['insurance', 'subrogation', 'waiver'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'insurance',
    title: 'Self-Insurance (Vendor Pushback)',
    content: `<p>Provider may, at its option, satisfy any or all of the insurance requirements in this Section through a program of self-insurance, provided that Provider maintains a tangible net worth of at least {{selfInsuranceNetWorth}} and provides Customer with reasonable evidence of its financial responsibility upon request.</p>`,
    tags: ['insurance', 'self-insurance'],
    riskRating: 'unfavorable',
    isApproved: false,
  },

  // ─── Compliance with Laws ───────────────────────────────────────────────
  {
    categorySlug: 'compliance',
    title: 'General Compliance with Laws',
    content: `<p>Each party will comply with all federal, state, and local laws, rules, and regulations applicable to its performance under this Agreement, and will obtain and maintain all licenses, permits, and authorizations required for such performance.</p>`,
    tags: ['compliance', 'general'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'compliance',
    title: 'Anti-Bribery and Anti-Corruption',
    content: `<p>Each party will comply with the U.S. Foreign Corrupt Practices Act of 1977, the UK Bribery Act 2010, and all other applicable anti-bribery and anti-corruption laws. Neither party (nor anyone on its behalf) will offer, give, request, or accept any payment or benefit that would violate such laws.</p>`,
    tags: ['compliance', 'anti-corruption', 'fcpa', 'ukba'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'compliance',
    title: 'Sanctions and Export Controls',
    content: `<p>Each party will comply with all applicable trade sanctions and export-control laws and regulations administered by the United States (including OFAC and the U.S. Department of Commerce), the European Union, the United Kingdom, the United Nations, and any other relevant authority. Neither party will provide access to the Services to any person or entity subject to such sanctions.</p>`,
    tags: ['compliance', 'sanctions', 'export-controls', 'ofac'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'compliance',
    title: 'Modern Slavery and Human Trafficking',
    content: `<p>Each party represents that it has, and will maintain, policies and procedures designed to prevent slavery, human trafficking, forced labor, and child labor in its operations and supply chains, in compliance with applicable laws (including the UK Modern Slavery Act 2015 and the California Transparency in Supply Chains Act).</p>`,
    tags: ['compliance', 'modern-slavery', 'esg'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'compliance',
    title: 'Conflict Minerals',
    content: `<p>To the extent applicable, each party will comply with Section 1502 of the Dodd-Frank Wall Street Reform and Consumer Protection Act and the SEC's implementing rules regarding conflict minerals.</p>`,
    tags: ['compliance', 'conflict-minerals'],
    riskRating: 'standard',
    isApproved: true,
  },

  // ─── Dispute Resolution ─────────────────────────────────────────────────
  {
    categorySlug: 'dispute',
    title: 'Governing Law — Delaware',
    content: `<p>This Agreement is governed by and construed in accordance with the laws of the State of Delaware, without giving effect to its conflict-of-laws principles. The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Agreement.</p>`,
    tags: ['dispute', 'governing-law', 'delaware'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'dispute',
    title: 'Governing Law — New York',
    content: `<p>This Agreement is governed by and construed in accordance with the laws of the State of New York, without giving effect to its conflict-of-laws principles.</p>`,
    tags: ['dispute', 'governing-law', 'new-york'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'dispute',
    title: 'Jurisdiction and Venue — Federal Court',
    content: `<p>The parties consent to the exclusive jurisdiction and venue of the state and federal courts located in {{venueLocation}} for any action arising out of or relating to this Agreement, and each party waives any objection based on inconvenient forum.</p>`,
    tags: ['dispute', 'jurisdiction', 'venue', 'courts'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'dispute',
    title: 'Arbitration — AAA Commercial Rules',
    content: `<p>Any dispute arising out of or relating to this Agreement will be finally resolved by binding arbitration administered by the American Arbitration Association under its Commercial Arbitration Rules, by a single arbitrator. The seat of arbitration is {{arbitrationSeat}}, and the language of arbitration is English. The arbitrator may award injunctive or other equitable relief in addition to damages. Judgment on the award may be entered in any court of competent jurisdiction.</p>`,
    tags: ['dispute', 'arbitration', 'aaa'],
    riskRating: 'neutral',
    isApproved: true,
  },
  {
    categorySlug: 'dispute',
    title: 'Jury Trial Waiver',
    content: `<p>EACH PARTY KNOWINGLY AND VOLUNTARILY WAIVES ITS RIGHT TO A TRIAL BY JURY IN ANY ACTION ARISING OUT OF OR RELATING TO THIS AGREEMENT.</p>`,
    tags: ['dispute', 'jury-waiver'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'dispute',
    title: 'Equitable Relief',
    content: `<p>Each party acknowledges that a breach of the confidentiality or intellectual property provisions of this Agreement may cause irreparable harm for which monetary damages would be inadequate, and that the non-breaching party may seek temporary, preliminary, or permanent injunctive relief, without the requirement of posting a bond, in addition to any other remedies available at law or in equity.</p>`,
    tags: ['dispute', 'injunctive', 'equitable'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'dispute',
    title: 'Escalation Before Litigation',
    content: `<p>Before filing any action arising out of or relating to this Agreement, the parties will first attempt in good faith to resolve the dispute through escalation to designated senior executives of each party, who will meet (in person or by telephone) within fifteen (15) days of a written escalation notice. This Section does not prevent either party from seeking immediate equitable relief.</p>`,
    tags: ['dispute', 'escalation', 'good-faith'],
    riskRating: 'favorable',
    isApproved: true,
  },

  // ─── Assignment & Change of Control ─────────────────────────────────────
  {
    categorySlug: 'assignment-change',
    title: 'Assignment — Consent Required',
    content: `<p>Neither party may assign or transfer this Agreement (whether by operation of law, merger, sale of assets, or otherwise) without the other party's prior written consent (not to be unreasonably withheld, conditioned, or delayed), except that either party may assign this Agreement, without consent, to an Affiliate or to a successor in connection with a merger, acquisition, consolidation, or sale of all or substantially all of its assets or business, provided that the successor agrees in writing to be bound by this Agreement.</p>`,
    tags: ['assignment', 'consent'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'assignment-change',
    title: 'Change of Control — Termination Right',
    content: `<p>Customer may terminate this Agreement upon thirty (30) days' written notice if Provider undergoes a change of control to a competitor of Customer, as reasonably identified by Customer. "Change of control" means any transaction in which more than fifty percent (50%) of the voting securities or equivalent interests of a party are transferred to a third party, or any sale of all or substantially all of a party's assets.</p>`,
    tags: ['change-of-control', 'termination', 'competitor'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'assignment-change',
    title: 'Successors and Assigns',
    content: `<p>This Agreement is binding on, and inures to the benefit of, the parties and their respective permitted successors and assigns.</p>`,
    tags: ['assignment', 'successors'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'assignment-change',
    title: 'No Third-Party Beneficiaries',
    content: `<p>This Agreement is for the sole benefit of the parties and their permitted successors and assigns, and is not intended to confer any rights or remedies on any other person or entity.</p>`,
    tags: ['third-party-beneficiaries'],
    riskRating: 'standard',
    isApproved: true,
  },

  // ─── Force Majeure ──────────────────────────────────────────────────────
  {
    categorySlug: 'force-majeure',
    title: 'Force Majeure — Excused Performance',
    content: `<p>Neither party will be liable for any failure or delay in performance (other than payment obligations) caused by events beyond its reasonable control, including acts of God, war, terrorism, riots, fire, flood, earthquake, pandemic, governmental action, labor disputes (other than those involving the affected party's own workforce), and failures or delays of third-party providers, telecommunications, or utilities ("Force Majeure"), provided that the affected party promptly notifies the other party of the Force Majeure and uses commercially reasonable efforts to resume performance.</p>`,
    tags: ['force-majeure', 'excused-performance'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'force-majeure',
    title: 'Force Majeure — Termination for Prolonged Event',
    content: `<p>If a Force Majeure event continues for more than thirty (30) consecutive days, either party may terminate this Agreement upon written notice to the other party, in which case Provider will refund any prepaid, unused fees on a pro-rata basis.</p>`,
    tags: ['force-majeure', 'prolonged', 'termination'],
    riskRating: 'favorable',
    isApproved: true,
  },
  {
    categorySlug: 'force-majeure',
    title: 'Force Majeure — Mitigation Duty',
    content: `<p>The party affected by a Force Majeure event will use commercially reasonable efforts to mitigate the impact and to resume performance as soon as reasonably practicable. The affected party will keep the other party reasonably informed of the status of the Force Majeure event and its mitigation efforts.</p>`,
    tags: ['force-majeure', 'mitigation'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'force-majeure',
    title: 'Pandemic-Specific Force Majeure',
    content: `<p>For the avoidance of doubt, Force Majeure includes epidemics, pandemics, public health emergencies, and any related governmental restrictions (including shelter-in-place orders, business closures, and travel restrictions), to the extent such events materially impact a party's ability to perform.</p>`,
    tags: ['force-majeure', 'pandemic', 'covid'],
    riskRating: 'standard',
    isApproved: true,
  },

  // ─── Notices & Miscellaneous ────────────────────────────────────────────
  {
    categorySlug: 'notices-misc',
    title: 'Notices',
    content: `<p>All notices under this Agreement must be in writing and delivered by (a) hand; (b) overnight courier with tracking; or (c) certified mail, return receipt requested. Notices are deemed given upon receipt at the address set forth on the signature page, or such other address as a party may designate by written notice. Routine operational communications may be sent by email to the parties' designated contact representatives.</p>`,
    tags: ['notices', 'communications'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'notices-misc',
    title: 'Entire Agreement',
    content: `<p>This Agreement, together with any exhibits, schedules, SOWs, and Order Forms executed by the parties, constitutes the entire agreement of the parties with respect to its subject matter and supersedes all prior or contemporaneous agreements, communications, and understandings (whether written or oral) on that subject.</p>`,
    tags: ['entire-agreement', 'merger'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'notices-misc',
    title: 'Amendments',
    content: `<p>This Agreement may be amended only by a writing signed by an authorized representative of each party. No course of dealing, course of performance, or trade usage will amend this Agreement.</p>`,
    tags: ['amendments', 'modifications'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'notices-misc',
    title: 'Severability',
    content: `<p>If any provision of this Agreement is held to be invalid or unenforceable, the remaining provisions will continue in full force and effect, and the invalid or unenforceable provision will be modified to the minimum extent necessary to make it valid and enforceable while preserving the parties' intent.</p>`,
    tags: ['severability'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'notices-misc',
    title: 'Waiver',
    content: `<p>No waiver of any right or remedy under this Agreement is effective unless in writing and signed by the waiving party. A waiver of any breach is not a waiver of any subsequent breach.</p>`,
    tags: ['waiver'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'notices-misc',
    title: 'Counterparts and Electronic Signatures',
    content: `<p>This Agreement may be executed in counterparts, each of which is deemed an original and all of which together constitute one instrument. Signatures delivered by electronic means (including DocuSign or PDF) have the same legal effect as original ink signatures.</p>`,
    tags: ['counterparts', 'electronic-signature'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'notices-misc',
    title: 'Independent Contractors',
    content: `<p>The parties are independent contractors. Nothing in this Agreement creates a partnership, joint venture, employment, or agency relationship between the parties. Neither party has authority to bind the other party.</p>`,
    tags: ['independent-contractor', 'relationship'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'notices-misc',
    title: 'Publicity',
    content: `<p>Neither party will issue any press release or public statement regarding this Agreement without the other party's prior written consent. Either party may identify the other in customer or vendor lists and may respond accurately to inquiries about the existence of the business relationship.</p>`,
    tags: ['publicity', 'press-release'],
    riskRating: 'standard',
    isApproved: true,
  },

  // ─── Service Levels ─────────────────────────────────────────────────────
  {
    categorySlug: 'service-levels',
    title: 'Uptime Commitment — 99.9%',
    content: `<p>Provider will use commercially reasonable efforts to make the Services available at least ninety-nine and nine-tenths percent (99.9%) of the time, measured monthly, excluding Scheduled Maintenance and Force Majeure events. Provider will provide at least seventy-two (72) hours' prior notice of Scheduled Maintenance, which will be conducted outside of Customer's normal business hours where reasonably practicable.</p>`,
    tags: ['sla', 'uptime', '99.9'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'service-levels',
    title: 'Service Credits',
    content: `<p>If the Services do not meet the uptime commitment in a given month, Customer is entitled to a service credit, calculated as a percentage of the monthly fees for the affected Services, according to the following schedule: (a) 99.0% – 99.9% uptime: 10% credit; (b) 95.0% – 98.9% uptime: 25% credit; (c) below 95.0% uptime: 50% credit. Service credits are Customer's sole and exclusive remedy for any failure to meet the uptime commitment.</p>`,
    tags: ['sla', 'service-credits'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'service-levels',
    title: 'Severity Levels and Response Times',
    content: `<p>Provider will respond to support requests according to the following targets: (a) Severity 1 (Critical — Services completely unavailable): initial response within 1 hour, target resolution within 4 hours; (b) Severity 2 (High — major feature unavailable, workaround unavailable): initial response within 4 hours, target resolution within 1 business day; (c) Severity 3 (Medium — minor feature impacted): initial response within 1 business day, target resolution within 5 business days; (d) Severity 4 (Low — cosmetic or documentation): initial response within 5 business days.</p>`,
    tags: ['sla', 'support', 'response-time', 'severity'],
    riskRating: 'standard',
    isApproved: true,
  },
  {
    categorySlug: 'service-levels',
    title: 'Chronic Failure — Termination Right',
    content: `<p>If the Services fail to meet the uptime commitment for three (3) consecutive months, or for any four (4) months within a rolling twelve (12) month period, Customer may terminate this Agreement for cause upon written notice, and Provider will refund any prepaid, unused fees on a pro-rata basis.</p>`,
    tags: ['sla', 'chronic-failure', 'termination'],
    riskRating: 'favorable',
    isApproved: true,
  },
]
